export declare const card: string;
export declare const cardContent: string;
export declare const cardContentatSymbol: string;
export declare const cardImage: string;
export declare const cardImageContainer: string;
export declare const cardOptions: string;
export declare const cardSkeleton: string;
export declare const pulse: string;
export declare const spin: string;
